/**
 * @file This file contains the core logic for a PostgreSQL to WebSocket gateway.
 *
 * It acts as a PostgreSQL server, accepting client connections and translating their
 * queries into a custom, streaming JSON-based protocol over a WebSocket. This allows
 * standard PostgreSQL clients (like `psql` or `psycopg2`) to communicate with a
 * modern, web-native backend worker.
 *
 * The implementation is designed to be robust, handling connection state, streaming
 * responses, and error conditions gracefully.
 */

import { createServer, Server } from 'node:net';
import { PostgresConnection, FrontendMessageCode } from 'pg-gateway';
import WebSocket from 'ws';
import { Writer } from 'pg-protocol/dist/buffer-writer.js';

// --- Configuration (from environment variables with defaults) ---
const PG_PORT = parseInt(process.env.PG_PORT || '5432', 10);
const WORKER_URL = process.env.WORKER_URL || 'ws://localhost:8080';

// --- Types for the custom WebSocket Protocol ---

/**
 * Defines the structure of a job sent from the Gateway to the Worker.
 */
export type Job = {
    /** The API key, derived from the PG username. */
    api_key: string;
    /** The access token, derived from the PG password. */
    access_token: string;
    /** The raw SQL query string from the client. */
    query: string;
};

/**
 * Defines the structure of the 'schema' message payload from the Worker.
 */
export type WorkerSchema = {
    columns: { name: string; typeOID: number }[];
};

/**
 * Defines the structure of the 'data' message payload from the Worker.
 * It's an array of rows, where each row is an array of column values.
 */
export type WorkerData = (string | null)[][];

/**
 * Defines the structure of the 'complete' message payload from the Worker.
 */
export type WorkerComplete = {
    commandTag: string;
    total_rows: number;
};

/**
 * Defines the structure of the 'error' message payload from the Worker.
 */
export type WorkerError = {
    message: string;
    code: string;
};

/**
 * A union type representing any message sent from the Worker to the Gateway.
 */
export type WorkerMessage = {
    /** A unique ID generated by the worker to correlate all messages for a single query. */
    query_id: string;
    /** The type of the message, determining how the payload should be interpreted. */
    type: 'schema' | 'data' | 'complete' | 'error';
    /** The data payload, whose structure depends on the message type. */
    payload: WorkerSchema | WorkerData | WorkerComplete | WorkerError;
};


// --- Constants ---

/**
 * Maps human-readable names to the numeric codes for PostgreSQL backend messages.
 * This improves readability and prevents magic numbers.
 */
const MSG_CODE = {
    ROW_DESCRIPTION: 84, // 'T'
    DATA_ROW: 68,        // 'D'
    COMMAND_COMPLETE: 67, // 'C'
};

/**
 * Maps human-readable names to standard PostgreSQL error codes.
 */
const PG_ERROR_CODES = {
    CONNECTION_FAILURE: '08006',
};

// --- Main Gateway Logic ---

/**
 * Creates and configures the PostgreSQL gateway server.
 * This is the main entry point for the application.
 * @returns A Node.js `net.Server` instance, ready to be started with `server.listen()`.
 */
export function createGateway(): Server {
    const server = createServer((socket) => {
        const credentialsStore: { user?: string; password?: string } = {};

        /**
         * The state for the current, single in-flight query on this connection.
         * This simple state machine ensures that only one query is processed at a time per connection.
         * A more advanced implementation could use a Map keyed by queryId to handle multiple concurrent in-flight queries.
         */
        let inFlightQuery: {
            isSchemaSent: boolean;
            resolve: () => void;
            reject: (err: Error) => void;
        } | null = null;

        const ws = new WebSocket(WORKER_URL);

        const connection = new PostgresConnection(socket, {
            serverVersion: '15.0 (Streaming Gateway)',
            authMode: 'cleartextPassword',
            /**
             * This hook captures the user's credentials upon connection.
             * For this example, it accepts any credentials and stores them
             * to be forwarded to the worker with each query.
             */
            validateCredentials: (credentials) => {
                credentialsStore.user = credentials.user;
                credentialsStore.password = credentials.password;
                return true;
            },
            /**
             * This hook is the core of the gateway's logic. It intercepts raw 'Query' messages
             * from the client and orchestrates the communication with the backend worker.
             */
            onMessage: async (data, state) => {
                if (!state.isAuthenticated) return false;

                if (data[0] === FrontendMessageCode.Query) {
                    const query = data.toString('utf8', 5, data.length - 1);
                    console.log(`[Gateway] Received query: "${query}"`);

                    // If the worker is not connected, immediately fail the query with a recoverable error.
                    if (ws.readyState !== WebSocket.OPEN) {
                        connection.sendError({ severity: 'ERROR', code: PG_ERROR_CODES.CONNECTION_FAILURE, message: 'Backend worker is not connected.' });
                        connection.sendReadyForQuery();
                        return true;
                    }

                    const job: Partial<Job> = {
                        api_key: credentialsStore.user,
                        access_token: credentialsStore.password,
                        query: query,
                    };

                    // Enforce one query at a time per connection.
                    if (inFlightQuery) {
                        connection.sendError({ severity: 'ERROR', code: '55P03', message: 'Gateway is busy with another query.' });
                        connection.sendReadyForQuery();
                        return true;
                    }

                    // This promise represents the entire lifecycle of the query. It will be resolved
                    // by the 'complete' message handler or rejected by the 'error' handler or a connection drop.
                    const queryDonePromise = new Promise<void>((resolve, reject) => {
                        inFlightQuery = { isSchemaSent: false, resolve, reject };
                    });

                    ws.send(JSON.stringify(job));

                    // The gateway now waits until the query is fully processed.
                    await queryDonePromise;

                    inFlightQuery = null;
                    return true; // We have handled this message.
                }
                return false; // Let pg-gateway handle other message types.
            },
        });

        /**
         * This handler processes all incoming messages from the worker for the current connection.
         * It acts as a state machine, processing `schema`, `data`, `complete`, and `error`
         * messages in the expected order.
         */
        ws.on('message', (data) => {
            if (!inFlightQuery) return; // Ignore messages if we're not expecting any.

            const message: WorkerMessage = JSON.parse(data.toString());

            switch (message.type) {
                case 'schema':
                    // The first message must be the schema.
                    sendRowDescription(connection, (message.payload as WorkerSchema).columns);
                    inFlightQuery.isSchemaSent = true;
                    break;

                case 'data':
                    // Ensure schema was sent first to adhere to the protocol.
                    if (!inFlightQuery.isSchemaSent) {
                        const err = new Error('Worker sent data before schema.');
                        connection.sendError({ severity: 'ERROR', code: 'XX000', message: err.message });
                        inFlightQuery.reject(err);
                    } else {
                        (message.payload as WorkerData).forEach(row => sendDataRow(connection, row));
                    }
                    break;

                case 'complete':
                    // This is the final success message. Send CommandComplete and resolve the promise.
                    sendCommandComplete(connection, (message.payload as WorkerComplete).commandTag);
                    connection.sendReadyForQuery();
                    inFlightQuery.resolve();
                    break;

                case 'error':
                    // The query failed. Send an error and reject the promise.
                    const errorPayload = message.payload as WorkerError;
                    connection.sendError({ severity: 'ERROR', code: errorPayload.code, message: errorPayload.message });
                    connection.sendReadyForQuery();
                    inFlightQuery.reject(new Error(errorPayload.message));
                    break;
            }
        });

        /**
         * A unified cleanup function to ensure all resources are released when either
         * the PG client or the WebSocket connection is terminated.
         */
        const cleanup = () => {
            if (inFlightQuery) {
                inFlightQuery.reject(new Error('Connection closed unexpectedly.'));
            }
            if (ws.readyState === WebSocket.OPEN) ws.close();
            if (!socket.destroyed) socket.end();
        };
        ws.on('close', cleanup);
        ws.on('error', cleanup);
        socket.on('close', cleanup);
        socket.on('error', cleanup);
    });

    return server;
}


// --- Protocol Helper Functions ---

/**
 * Constructs and sends a PostgreSQL `RowDescription` message.
 * @param conn The active PostgresConnection.
 * @param cols An array of column definitions from the worker.
 */
function sendRowDescription(conn: PostgresConnection, cols: { name: string; typeOID: number }[]) {
    const writer = new Writer();
    writer.addInt16(cols.length);
    cols.forEach(c => { writer.addCString(c.name); writer.addInt32(0); writer.addInt16(0); writer.addInt32(c.typeOID); writer.addInt16(-1); writer.addInt32(-1); writer.addInt16(0); });
    conn.sendData(writer.flush(MSG_CODE.ROW_DESCRIPTION));
}

/**
 * Constructs and sends a PostgreSQL `DataRow` message.
 * @param conn The active PostgresConnection.
 * @param row An array of string or null values representing a single row.
 */
function sendDataRow(conn: PostgresConnection, row: (string | null)[]) {
    const writer = new Writer();
    writer.addInt16(row.length);
    row.forEach(val => {
        if (val === null) writer.addInt32(-1); // -1 signifies a NULL value.
        else {
            const buffer = Buffer.from(val, 'utf8');
            writer.addInt32(buffer.length);
            writer.add(buffer);
        }
    });
    conn.sendData(writer.flush(MSG_CODE.DATA_ROW));
}

/**
 * Constructs and sends a PostgreSQL `CommandComplete` message.
 * @param conn The active PostgresConnection.
 * @param tag The command tag string (e.g., "SELECT 1").
 */
function sendCommandComplete(conn: PostgresConnection, tag: string) {
    const writer = new Writer();
    writer.addCString(tag);
    conn.sendData(writer.flush(MSG_CODE.COMMAND_COMPLETE));
}
